name: glowify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_splash_screen: 1.3.0
  badges: 3.1.2
  card_slider: 1.0.5
  carousel_slider: 5.0.0
  cloud_firestore: ^5.3.0
  cupertino_icons: ^1.0.2
  faker: ^2.2.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_database: ^11.1.0
  firebase_messaging: ^15.1.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.2
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get: 4.6.6
  google_fonts: 6.2.1
  google_sign_in: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^0.8.7
  intl: ^0.19.0
  introduction_screen: 3.1.14
  ionicons: 0.2.2
  page_transition: ^2.1.0
  permission_handler: ^11.3.1
  shared_preferences: 2.2.3
  # tflite: ^1.1.2
  skeletonizer: ^1.4.2
  tflite_v2: ^1.0.0
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
    - core/.env.dev
    - assets/face_health_detection/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
  uses-material-design: true
