name: glowify
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animated_splash_screen: 1.3.0
  badges: 3.1.2
  card_slider: 1.0.5
  carousel_slider: 5.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get: 4.6.6
  google_fonts: 6.2.1
  ionicons: 0.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - core/.env.dev
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
  uses-material-design: true
